version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "auto"
    schedule:
      interval: "daily"


  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    rebase-strategy: "auto"
    schedule:
      interval: "daily"
